spring.application.name=ai-pr-validation-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=aiprdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=springuser
spring.datasource.password=Spring@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=sha256=101131fbc1912b91bb655f07a655d892795cf531bdbaefbe8cb4d5fcb7f02204
app.jwt.expiration-ms=86400000

app.github.webhook-secret=${GITHUB_WEBHOOK_SECRET:change-me}
app.github.api-token=${GITHUB_API_TOKEN:}
app.github.api-base-url=https://api.github.com

app.ai.api-url=https://api.groq.com/openai/v1/chat/completions
app.ai.api-key=${AI_API_KEY}
app.ai.model=openai/gpt-oss-120b
app.ai.approval-threshold=70

spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5173
